apiVersion: v1
kind: PersistentVolume
metadata:
  name: reverse-proxy-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hubirto/Desktop/K3sServers/revers-proxy/data"
