apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      # hostNetwork: true
      containers:
      - name: lobby
        image: itzg/minecraft-server:java17
        ports:
        - containerPort: 25565
        env:
          - name: EULA
            value: "TRUE"
          - name: TYPE
            value: "PAPER"
        volumeMounts:
          - mountPath: /data
            name: lobby-pv-storage
      volumes:
      - name: lobby-pv-storage
        persistentVolumeClaim:
          claimName: lobby-pv-claim