apiVersion: v1
kind: PersistentVolume
metadata:
  name: surival-pv-volume
  labels:
    type: surival
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hubirto/Desktop/K3sServers/losurivalbby/data"
